<h1 style='color:blue;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

**Logistic Regression**

In [3]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

**SVM**

In [4]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.31296296296296294

**Random Forest**

In [10]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [27]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [28]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11]):
    print(train_index, test_index)

[ 3  4  5  6  7  8  9 10] [0 1 2]
[ 0  1  2  5  6  7  8  9 10] [3 4]
[ 0  1  2  3  4  7  8  9 10] [5 6]
[ 0  1  2  3  4  5  6  9 10] [7 8]
[0 1 2 3 4 5 6 7 8] [ 9 10]


**Use KFold for our digits example**

In [29]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [15]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [16]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [17]:
scores_rf

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

<h2 style='color:purple'>cross_val_score function</h2>

In [29]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [31]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89534884, 0.94991653, 0.90939597])

**svm model performance using cross_val_score**

In [32]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.39368771, 0.41068447, 0.45973154])

**random forest performance using cross_val_score**

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93521595, 0.94156928, 0.93288591])

cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [34]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8793698637138034

In [35]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9358915527370766

In [36]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9494121957589801

In [37]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9482877777434258

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 

<h2 style='color:purple'>Exercise</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [32]:
from sklearn.datasets import load_iris
data = load_iris()

In [33]:
from sklearn.model_selection import cross_val_score

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.data,data.target,test_size=0.3)

**Logistic regression model performance using cross_val_score**

In [38]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), data.data, data.target,cv=3)

array([0.96, 0.96, 0.94])

In [39]:
cross_val_score(SVC(gamma='auto'), data.data, data.target,cv=3)

array([0.98, 0.98, 0.96])

In [48]:
cross_val_score(DecisionTreeClassifier(criterion = 'gini'), data.data, data.target,cv=3)

array([0.98, 0.92, 0.96])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93656093, 0.95492487, 0.92821369])